### ISSUE TITLE
Join room

### ISSUE THREAD

**Issue by hothost87** [dc1014/cs3354-brogrammers#5]
Is there permission involved in joining rooms?

**Comment by dc1014** [comment]
My first issue, joy. 

I take it you feel we should include this feature? We could do it with JWT.

**Comment by hothost87** [comment]
just need clarification. Either way is fine for me. So if no permission is involved, that means anyone can join a chat room? Is there similar real-world app?

**Comment by dc1014** [comment]
Unfortunately, Twitch and YouTube do not offer private chat on live streams (or private streams for that matter), but this would be analogous to supporting that feature.

**Comment by hothost87** [comment]
I see. Thanks for the explanation. Make sense. You can leave it as it is.

**Comment by dc1014** [comment]
Thanks for your review, Dr. Wei. We may just include authorization and authentication, regardless. Have a good evening!
